### PR TITLE
Modified script

### PR DESCRIPTION
**Pull request by lingrottin**
- Fix shebang
- Values should be put at the top of the script
- Values should be named with upper-case alphabets
- Common changes
太晚了没来得及改readme，抱歉（明天再

### CODE REVIEW

**Comment by lingrottin** [comment]
I think I am an sb.

**Review by LGY07 — APPROVED** [review]

**Review by LGY07 — APPROVED** [review]

**Comment by LGY07** [comment]
Don't read me.

**Review by LGY07 — APPROVED** [review]

**Comment by lingrottin** [comment]
> Don't read me.

I want to read it.

**Review by LGY07 — APPROVED** [review]

**Comment by LGY07** [comment]
> > Don't read me.
> 
> I don't want to read it.

You do.

**Comment by lingrottin** [comment]
> > Don't read me.
> 
> I want to read it.
> 
> No,don't read me.



> > Don't read me.
> 
> I don't want to read it.

（That's not what I said)
I'd like to read it very much.

**Comment by LGY07** [comment]
> > > Don't read me.
> > 
> > 
> > I want to read it.
> > No,don't read me.
> 
> > > Don't read me.
> > 
> > 
> > I don't want to read it.
> 
> （That's what I said) I'd dislike to read it very much.

You always read the README!

**Comment by LGY07** [comment]
> I think I am an sb.

I feel so too

**Review by lingrottin — COMMENTED** [review]
Awesome

**Comment by lingrottin** [comment]
> > > Don't read me.
> > 
> > I don't want to read it.
> 
> I want to be a Pac-Man!!!!!

Good choice, what a wise man!

**Pull request merged**
